### ISSUE TITLE
Creating Email PKI User does not work

### ISSUE THREAD

**Issue by alfonsrv** [esurdam/go-sophos#5]
When creating a user via REST API for the `emailpki` with valid certificates, the user is neither shown in the web interface, nor does signing/encrypting/decrypting work.

**Comment by esurdam** [comment]
hey @alfonsrv, sorry for the late update -- can you provide a sample of the request you are making? Are you properly passing headers which will resolve and close the session?

**Comment by alfonsrv** [comment]
Any correlation with yesterday's EOL notice triggering this reply? :P

Was my bad. I forgot calling the `api/nodes/emailpki.objects.users` endpoint after creation.
